name: 'Analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Analytics:

    # -----------------------
    # Staging layer
    # -----------------------
    staging:
      +materialized: table
      +post-hook:
        - "GRANT SELECT ON {{ this }} TO PUBLIC"
        - >
          INSERT INTO audit_log(model_name, row_count, run_time)
          SELECT '{{ this.name }}', COUNT(*), CURRENT_TIMESTAMP FROM {{ this }}

    # -----------------------
    # Transformation layer
    # -----------------------
    transformation:
      +materialized: view
      +post-hook:
        - "GRANT SELECT ON {{ this }} TO PUBLIC"
        - >
          INSERT INTO audit_log(model_name, row_count, run_time)
          SELECT '{{ this.name }}', COUNT(*), CURRENT_TIMESTAMP FROM {{ this }}

    # -----------------------
    # Business layer
    # -----------------------
    business:
      +materialized: table
      +post-hook:
        - "GRANT SELECT ON {{ this }} TO PUBLIC"
        - >
          INSERT INTO audit_log(model_name, row_count, run_time)
          SELECT '{{ this.name }}', COUNT(*), CURRENT_TIMESTAMP FROM {{ this }}
