
models:
  - name: dim_customer
    description: "Customer dimension"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: customer_name_upper
        tests:
          - not_null

  - name: dim_part
    description: "Part dimension"
    columns:
      - name: part_id
        tests:
          - not_null
          - unique
      - name: part_name
        tests:
          - not_null

  - name: dim_supplier
    description: "Supplier dimension"
    columns:
      - name: supplier_id
        tests:
          - not_null
          - unique
      - name: supplier_name_upper
        tests:
          - not_null


  - name: fact_orders
    description: "Fact table containing order details"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: part_id
        tests:
          - relationships:
              to: ref('dim_part')
              field: part_id
      - name: supplier_id
        tests:
          - relationships:
              to: ref('dim_supplier')
              field: supplier_id